version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./flaskapp.sql:/docker-entrypoint-initdb.d/flaskapp.sql
    networks:
      - flask-net

  flask-app:
    image: devopsdhruvjain/flask-app:v1
    container_name: flask-app
    environment:
      DB_USER: flaskuser
      DB_PASSWORD: root
      DB_HOST: mysql
      DB_NAME: flaskapp
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - flask-net

networks:
  flask-net:
    driver: bridge

volumes:
  mysql-data: